# Generated by Django 5.0.4 on 2024-06-17 20:17

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='artista/')),
                ('nombre', models.CharField(max_length=75)),
                ('apellido', models.CharField(max_length=75)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', django_countries.fields.CountryField(max_length=2)),
                ('bibliografia', models.TextField(blank=True, max_length=700)),
                ('tipo_de_Artista', models.CharField(choices=[('ACTOR', 'Actor'), ('DIRECTOR', 'Director')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('sinopsis', models.TextField(max_length=700)),
                ('cartelera', models.ImageField(blank=True, null=True, upload_to='pelicula/')),
                ('estreno', models.DateField()),
                ('rank', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('artista', models.ManyToManyField(to='fuente.artista')),
                ('categoria', models.ManyToManyField(help_text='Seleccione la/s categoria/s', to='fuente.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('comentario', models.TextField(blank=True, max_length=1000)),
                ('puntaje', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('censura', models.BooleanField(default=False)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuente.pelicula')),
            ],
        ),
    ]
