# Generated by Django 5.0.4 on 2024-06-06 15:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ImageField(null=True, upload_to='')),
                ('nombre', models.CharField(max_length=75)),
                ('apellido', models.CharField(max_length=75)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('bibliografia', models.TextField(blank=True, max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ImageField(null=True, upload_to='')),
                ('nombre', models.CharField(max_length=75)),
                ('apellido', models.CharField(max_length=75)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('bibliografia', models.TextField(blank=True, max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sinopsis', models.TextField(max_length=700)),
                ('cartelera', models.ImageField(null=True, upload_to='')),
                ('lanzamiento', models.DateField()),
                ('rank', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('actores', models.ManyToManyField(to='fuente.actor')),
                ('categoria', models.ManyToManyField(help_text='Seleccione la/s categoria/s', to='fuente.categoria')),
                ('director', models.ManyToManyField(to='fuente.director')),
            ],
        ),
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('comentario', models.TextField(blank=True, max_length=1000, null=True)),
                ('puntaje', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuente.pelicula')),
            ],
        ),
    ]
