# Generated by Django 5.0.4 on 2024-06-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='carteleras/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='carteleras/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='cartelera',
            field=models.ImageField(blank=True, null=True, upload_to='pelicula/'),
        ),
    ]
