# Generated by Django 5.0.4 on 2024-06-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='tipo_de_Artista',
            field=models.CharField(choices=[('ACTOR', 'Actor'), ('DIRECTOR', 'Director')], default='ACTOR', max_length=10),
        ),
    ]
