# Generated by Django 5.0.4 on 2024-04-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='fotografia',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='director',
            name='fotografia',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='cartelera',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
