# Generated by Django 5.0.4 on 2024-06-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuente', '0002_alter_artista_tipo_de_artista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='censura',
            field=models.CharField(choices=[('CENSURADO', 'Censurado'), ('PUBLICADO', 'Publico'), ('EN_REVISION', 'En revisión')], default='EN_REVISION', max_length=11),
        ),
    ]
