# Generated by Django 5.0.4 on 2024-06-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuente', '0002_alter_actor_fotografia_alter_director_fotografia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/actor'),
        ),
        migrations.AlterField(
            model_name='director',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/director'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='cartelera',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/pelicula'),
        ),
    ]
