# Generated by Django 5.0.4 on 2024-04-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuente', '0003_pelicula_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='comentario',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
