# Generated by Django 5.0.4 on 2024-06-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuente', '0003_alter_critica_censura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='critica',
            old_name='censura',
            new_name='estado_de_critica',
        ),
    ]
