# Generated by Django 5.0.4 on 2024-04-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuente', '0004_alter_critica_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='catergoria',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='categoria',
            field=models.ManyToManyField(help_text='Seleccione la/s categoria/s', to='fuente.categoria'),
        ),
    ]
