# Generated by Django 5.0.4 on 2024-06-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuente', '0004_rename_censura_critica_estado_de_critica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
