# Generated by Django 5.0.4 on 2024-06-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuente', '0005_rename_lanzamiento_pelicula_estreno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='actor/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='director/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='cartelera',
            field=models.ImageField(blank=True, null=True, upload_to='pelicula/'),
        ),
    ]
