# Generated by Django 5.0.4 on 2024-06-12 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuente', '0006_alter_actor_fotografia_alter_director_fotografia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='tipo',
            new_name='categoria',
        ),
    ]
