# Generated by Django 5.0.4 on 2024-06-12 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuente', '0008_globalconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalConfiguration',
        ),
    ]
