# Generated by Django 5.0.4 on 2024-06-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuente', '0011_alter_actor_apellido_alter_actor_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='apellido',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='actor',
            name='nombre',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='director',
            name='apellido',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='director',
            name='nombre',
            field=models.CharField(max_length=75),
        ),
    ]
