# Generated by Django 5.0.4 on 2024-06-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuente', '0006_alter_critica_pelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='comentario',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
